import { prismaService } from "../db";
import { generateId } from "../lib/utils/snowflake.utils";

export class ChatService {
    async getAllChats(projectId: bigint) {
        const prisma = prismaService.getClient();

        const categories = await prisma.category.findMany({
            where: {
                project_id: projectId,
            },
            orderBy: { position: "asc" },
            include: {
                chats: {
                    orderBy: { created_at: "asc" }
                }
            }
        });

        const uncategorizedChats = await prisma.chat.findMany({
            where: {
                project_id: projectId,
                category_id: null,
            },
            orderBy: { created_at: "asc" },
        });

        return [
            categories.map(category => ({
                id: category.id,
                name: category.name,
                chats: category.chats
            })),
            {
                id: null,
                name: "Chats",
                chats: uncategorizedChats,
            }
        ];
    }

    async createNewChat(message: string, userId: bigint, projectId: bigint) {
        const prisma = prismaService.getClient();

        const name = "Test name"; //! UPDATE CHAT NAME TO BE GENERATED BY LIGHTWEIGHT AI MODEL LATER
        const id = generateId();

        const chat = await prisma.chat.create({
            data: {
                id,
                name,
                owner_id: userId,
                project_id: projectId
            }
        });

        return chat;
    }
}

export const chatService = new ChatService();