import { toLowerCase } from "zod";
import { prismaService, scyllaService } from "../db";
import { NotFoundError } from "../lib/exceptions";
import { generateId } from "../lib/utils/snowflake.utils";

export class ChatService {
    async getAllChats(projectId: bigint) {
        const prisma = prismaService.getClient();

        const chats = await prisma.chat.findMany({
            where: { project_id: projectId },
            orderBy: { created_at: "asc" },
        });

        const sortedChats = chats.reduce<{ 
            pinned: typeof chats,
            chats: typeof chats,
        }>(
            (acc, chat) => {
                if (chat.pinned) {
                acc.pinned.push(chat);
                } else {
                acc.chats.push(chat);
                }
                return acc;
            },
            { pinned: [], chats: [] }
        );

        return sortedChats;
    }

    async createNewChat(message: string, userId: bigint, projectId: bigint) {
        const prisma = prismaService.getClient();

        const name = "Test name"; //! UPDATE CHAT NAME TO BE GENERATED BY LIGHTWEIGHT AI MODEL LATER
        const id = generateId();

        const chat = await prisma.chat.create({
            data: {
                id,
                name,
                owner_id: userId,
                project_id: projectId
            }
        });

        return chat;
    }

    async updateChatName(name: string, userId: bigint, chatId: bigint) {
        const prisma = prismaService.getClient();

        const chat = await prisma.chat.update({
            where: {
                id: chatId,
                owner_id: userId,
            },
            data: {
                name,
            }
        });

        return chat;
    }

    async deleteChat(userId: bigint, chatId: bigint) {
        const prisma = prismaService.getClient();

        const chat = await prisma.chat.delete({
            where: {
                id: chatId,
                owner_id: userId,
            }
        });

        return chat;
    }

    async pinChat(userId: bigint, chatId: bigint) {
        const prisma = prismaService.getClient();

        const chat = await prisma.chat.findUnique({
            where: { id: chatId },
        });

        if (!chat) throw new NotFoundError("Chat not found");

        const updatedChat = await prisma.chat.update({
            where: {
                id: chatId,
                owner_id: userId,
            },
            data: {
                pinned: !chat.pinned
            }
        });

        return updatedChat;
    }

    async getMessages(chatId: string, limit: string, direction?: string, fromMessageId?: string) {
        const scylla = scyllaService.getClient();

        const parsedLimit = Math.min(parseInt(limit as string), 100);

        let query = `
            SELECT * FROM messages WHERE chat_id = ?
        `

        const params: (string | number)[] = [chatId];

        if (fromMessageId) {
            if (direction?.toLowerCase() === "before") {
                query += ` AND message_id < ?`;
                params.push(fromMessageId);
                query += ` ORDER BY message_id DESC`;
            }
            else if (direction?.toLowerCase() === "after") {
                query += ` AND message_id > ?`;
                params.push(fromMessageId);
                query += ` ORDER BY message_id ASC`;
            }
        } else {
            query += ` ORDER BY message_id DESC`;
        }

        query += ` LIMIT ?`;
        params.push(parsedLimit);

        const result = await scylla.execute(query, params, { prepare: true });
        const messages = result.rows;

        return messages;
    }
}

export const chatService = new ChatService();